{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "72f70cbc",
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'null' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[31m---------------------------------------------------------------------------\u001b[39m",
      "\u001b[31mNameError\u001b[39m                                 Traceback (most recent call last)",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[3]\u001b[39m\u001b[32m, line 57\u001b[39m\n\u001b[32m     53\u001b[39m     \u001b[33m\"if torch.cuda.is_available():\\n\"\u001b[39m,\n\u001b[32m     54\u001b[39m     \u001b[33m\"    print(f'GPU: {torch.cuda.get_device_name(0)}')\\n\"\u001b[39m,\n\u001b[32m     55\u001b[39m     \u001b[33m\"    print(f'VRAM: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB')\"\u001b[39m\n\u001b[32m     56\u001b[39m    ],\n\u001b[32m---> \u001b[39m\u001b[32m57\u001b[39m    \u001b[33m\"execution_count\"\u001b[39m: null,\n\u001b[32m     58\u001b[39m    \u001b[33m\"outputs\"\u001b[39m: []\n\u001b[32m     59\u001b[39m   },\n\u001b[32m     60\u001b[39m   {\n",
      "\u001b[31mNameError\u001b[39m: name 'null' is not defined"
     ]
    }
   ],
   "source": [
    "{\n",
    " \"cells\": [\n",
    "  {\n",
    "   \"cell_type\": \"code\",\n",
    "   \"execution_count\": null,\n",
    "   \"id\": \"72f70cbc\",\n",
    "   \"metadata\": {},\n",
    "   \"outputs\": [\n",
    "    {\n",
    "     \"ename\": \"NameError\",\n",
    "     \"evalue\": \"name 'null' is not defined\",\n",
    "     \"output_type\": \"error\",\n",
    "     \"traceback\": [\n",
    "      \"\\u001b[31m---------------------------------------------------------------------------\\u001b[39m\",\n",
    "      \"\\u001b[31mNameError\\u001b[39m                                 Traceback (most recent call last)\",\n",
    "      \"\\u001b[36mCell\\u001b[39m\\u001b[36m \\u001b[39m\\u001b[32mIn[3]\\u001b[39m\\u001b[32m, line 57\\u001b[39m\\n\\u001b[32m     53\\u001b[39m     \\u001b[33m\\\"if torch.cuda.is_available():\\\\n\\\"\\u001b[39m,\\n\\u001b[32m     54\\u001b[39m     \\u001b[33m\\\"    print(f'GPU: {torch.cuda.get_device_name(0)}')\\\\n\\\"\\u001b[39m,\\n\\u001b[32m     55\\u001b[39m     \\u001b[33m\\\"    print(f'VRAM: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB')\\\"\\u001b[39m\\n\\u001b[32m     56\\u001b[39m    ],\\n\\u001b[32m---> \\u001b[39m\\u001b[32m57\\u001b[39m    \\u001b[33m\\\"execution_count\\\"\\u001b[39m: null,\\n\\u001b[32m     58\\u001b[39m    \\u001b[33m\\\"outputs\\\"\\u001b[39m: []\\n\\u001b[32m     59\\u001b[39m   },\\n\\u001b[32m     60\\u001b[39m   {\\n\",\n",
    "      \"\\u001b[31mNameError\\u001b[39m: name 'null' is not defined\"\n",
    "     ]\n",
    "    }\n",
    "   ],\n",
    "   \"source\": [\n",
    "    \"{\\n\",\n",
    "    \" \\\"nbformat\\\": 4,\\n\",\n",
    "    \" \\\"nbformat_minor\\\": 0,\\n\",\n",
    "    \" \\\"metadata\\\": {\\n\",\n",
    "    \"  \\\"colab\\\": {\\n\",\n",
    "    \"   \\\"provenance\\\": [],\\n\",\n",
    "    \"   \\\"gpuType\\\": \\\"T4\\\",\\n\",\n",
    "    \"   \\\"name\\\": \\\"colab_full_pipeline.ipynb\\\"\\n\",\n",
    "    \"  },\\n\",\n",
    "    \"  \\\"kernelspec\\\": {\\n\",\n",
    "    \"   \\\"name\\\": \\\"python3\\\",\\n\",\n",
    "    \"   \\\"display_name\\\": \\\"Python 3\\\"\\n\",\n",
    "    \"  },\\n\",\n",
    "    \"  \\\"accelerator\\\": \\\"GPU\\\"\\n\",\n",
    "    \" },\\n\",\n",
    "    \" \\\"cells\\\": [\\n\",\n",
    "    \"  {\\n\",\n",
    "    \"   \\\"cell_type\\\": \\\"markdown\\\",\\n\",\n",
    "    \"   \\\"metadata\\\": {},\\n\",\n",
    "    \"   \\\"source\\\": [\\n\",\n",
    "    \"    \\\"# Tool-Calling LLM Fine-Tune\\\\n\\\",\\n\",\n",
    "    \"    \\\"\\\\n\\\",\\n\",\n",
    "    \"    \\\"Complete pipeline:\\\\n\\\",\\n\",\n",
    "    \"    \\\"1. Setup and clone repo\\\\n\\\",\\n\",\n",
    "    \"    \\\"2. Install dependencies\\\\n\\\",\\n\",\n",
    "    \"    \\\"3. Generate training data\\\\n\\\",\\n\",\n",
    "    \"    \\\"4. Fine-tune with LoRA\\\\n\\\",\\n\",\n",
    "    \"    \\\"5. Merge and quantize\\\\n\\\",\\n\",\n",
    "    \"    \\\"6. Evaluate\\\\n\\\",\\n\",\n",
    "    \"    \\\"7. Launch demo\\\\n\\\",\\n\",\n",
    "    \"    \\\"\\\\n\\\",\\n\",\n",
    "    \"    \\\"**Set runtime to T4 GPU before running**\\\\n\\\",\\n\",\n",
    "    \"    \\\"Runtime → Change runtime type → T4 GPU\\\"\\n\",\n",
    "    \"   ]\\n\",\n",
    "    \"  },\\n\",\n",
    "    \"  {\\n\",\n",
    "    \"   \\\"cell_type\\\": \\\"code\\\",\\n\",\n",
    "    \"   \\\"metadata\\\": {},\\n\",\n",
    "    \"   \\\"source\\\": [\\n\",\n",
    "    \"    \\\"# Cell 1 — Check GPU\\\\n\\\",\\n\",\n",
    "    \"    \\\"import subprocess\\\\n\\\",\\n\",\n",
    "    \"    \\\"result = subprocess.run(['nvidia-smi'], capture_output=True, text=True)\\\\n\\\",\\n\",\n",
    "    \"    \\\"if result.returncode == 0:\\\\n\\\",\\n\",\n",
    "    \"    \\\"    print('GPU available:')\\\\n\\\",\\n\",\n",
    "    \"    \\\"    print(result.stdout[:300])\\\\n\\\",\\n\",\n",
    "    \"    \\\"else:\\\\n\\\",\\n\",\n",
    "    \"    \\\"    print('No GPU found')\\\\n\\\",\\n\",\n",
    "    \"    \\\"    print('Go to Runtime > Change runtime type > T4 GPU')\\\\n\\\",\\n\",\n",
    "    \"    \\\"\\\\n\\\",\\n\",\n",
    "    \"    \\\"import torch\\\\n\\\",\\n\",\n",
    "    \"    \\\"print(f'PyTorch: {torch.__version__}')\\\\n\\\",\\n\",\n",
    "    \"    \\\"print(f'CUDA: {torch.cuda.is_available()}')\\\\n\\\",\\n\",\n",
    "    \"    \\\"if torch.cuda.is_available():\\\\n\\\",\\n\",\n",
    "    \"    \\\"    print(f'GPU: {torch.cuda.get_device_name(0)}')\\\\n\\\",\\n\",\n",
    "    \"    \\\"    print(f'VRAM: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB')\\\"\\n\",\n",
    "    \"   ],\\n\",\n",
    "    \"   \\\"execution_count\\\": null,\\n\",\n",
    "    \"   \\\"outputs\\\": []\\n\",\n",
    "    \"  },\\n\",\n",
    "    \"  {\\n\",\n",
    "    \"   \\\"cell_type\\\": \\\"code\\\",\\n\",\n",
    "    \"   \\\"metadata\\\": {},\\n\",\n",
    "    \"   \\\"source\\\": [\\n\",\n",
    "    \"    \\\"# Cell 2 — Clone repo\\\\n\\\",\\n\",\n",
    "    \"    \\\"import os\\\\n\\\",\\n\",\n",
    "    \"    \\\"\\\\n\\\",\\n\",\n",
    "    \"    \\\"REPO_URL = 'https://github.com/LaraibKaleem/tool-calling-agent.git'\\\\n\\\",\\n\",\n",
    "    \"    \\\"\\\\n\\\",\\n\",\n",
    "    \"    \\\"if os.path.exists('tool-call-finetune'):\\\\n\\\",\\n\",\n",
    "    \"    \\\"    %cd tool-call-finetune\\\\n\\\",\\n\",\n",
    "    \"    \\\"    !git pull\\\\n\\\",\\n\",\n",
    "    \"    \\\"else:\\\\n\\\",\\n\",\n",
    "    \"    \\\"    !git clone {REPO_URL}\\\\n\\\",\\n\",\n",
    "    \"    \\\"    %cd tool-call-finetune\\\\n\\\",\\n\",\n",
    "    \"    \\\"\\\\n\\\",\\n\",\n",
    "    \"    \\\"!ls -la\\\"\\n\",\n",
    "    \"   ],\\n\",\n",
    "    \"   \\\"execution_count\\\": null,\\n\",\n",
    "    \"   \\\"outputs\\\": []\\n\",\n",
    "    \"  },\\n\",\n",
    "    \"  {\\n\",\n",
    "    \"   \\\"cell_type\\\": \\\"code\\\",\\n\",\n",
    "    \"   \\\"metadata\\\": {},\\n\",\n",
    "    \"   \\\"source\\\": [\\n\",\n",
    "    \"    \\\"# Cell 3 — Install dependencies\\\\n\\\",\\n\",\n",
    "    \"    \\\"!pip install -q -r requirements-train.txt\\\\n\\\",\\n\",\n",
    "    \"    \\\"\\\\n\\\",\\n\",\n",
    "    \"    \\\"import os\\\\n\\\",\\n\",\n",
    "    \"    \\\"os.environ['CMAKE_ARGS'] = '-DGGML_METAL=OFF -DGGML_CUDA=OFF'\\\\n\\\",\\n\",\n",
    "    \"    \\\"!pip install llama-cpp-python --force-reinstall --no-cache-dir -q\\\\n\\\",\\n\",\n",
    "    \"    \\\"\\\\n\\\",\\n\",\n",
    "    \"    \\\"print('Dependencies installed')\\\"\\n\",\n",
    "    \"   ],\\n\",\n",
    "    \"   \\\"execution_count\\\": null,\\n\",\n",
    "    \"   \\\"outputs\\\": []\\n\",\n",
    "    \"  },\\n\",\n",
    "    \"  {\\n\",\n",
    "    \"   \\\"cell_type\\\": \\\"code\\\",\\n\",\n",
    "    \"   \\\"metadata\\\": {},\\n\",\n",
    "    \"   \\\"source\\\": [\\n\",\n",
    "    \"    \\\"# Cell 4 — Generate training data\\\\n\\\",\\n\",\n",
    "    \"    \\\"!python src/generate_data.py --n 2000 --out-dir data\\\\n\\\",\\n\",\n",
    "    \"    \\\"\\\\n\\\",\\n\",\n",
    "    \"    \\\"import json, pathlib\\\\n\\\",\\n\",\n",
    "    \"    \\\"train = list(pathlib.Path('data/train.jsonl').open())\\\\n\\\",\\n\",\n",
    "    \"    \\\"val   = list(pathlib.Path('data/val.jsonl').open())\\\\n\\\",\\n\",\n",
    "    \"    \\\"print(f'Train examples: {len(train)}')\\\\n\\\",\\n\",\n",
    "    \"    \\\"print(f'Val examples  : {len(val)}')\\\\n\\\",\\n\",\n",
    "    \"    \\\"\\\\n\\\",\\n\",\n",
    "    \"    \\\"print('\\\\\\\\nSample example:')\\\\n\\\",\\n\",\n",
    "    \"    \\\"sample = json.loads(train[0])\\\\n\\\",\\n\",\n",
    "    \"    \\\"for msg in sample['messages']:\\\\n\\\",\\n\",\n",
    "    \"    \\\"    print(f\\\\\\\"  [{msg['role']:9s}] {msg['content'][:80]}\\\\\\\")\\\"\\n\",\n",
    "    \"   ],\\n\",\n",
    "    \"   \\\"execution_count\\\": null,\\n\",\n",
    "    \"   \\\"outputs\\\": []\\n\",\n",
    "    \"  },\\n\",\n",
    "    \"  {\\n\",\n",
    "    \"   \\\"cell_type\\\": \\\"code\\\",\\n\",\n",
    "    \"   \\\"metadata\\\": {},\\n\",\n",
    "    \"   \\\"source\\\": [\\n\",\n",
    "    \"    \\\"# Cell 5 — Fine-tune with LoRA\\\\n\\\",\\n\",\n",
    "    \"    \\\"# Takes about 25 minutes on T4 GPU\\\\n\\\",\\n\",\n",
    "    \"    \\\"!python src/train.py \\\\\\\\\\\\n\\\",\\n\",\n",
    "    \"    \\\"    --base-model Qwen/Qwen2.5-0.5B-Instruct \\\\\\\\\\\\n\\\",\\n\",\n",
    "    \"    \\\"    --output-dir artifacts/lora_adapter \\\\\\\\\\\\n\\\",\\n\",\n",
    "    \"    \\\"    --data-dir   data \\\\\\\\\\\\n\\\",\\n\",\n",
    "    \"    \\\"    --epochs 3 \\\\\\\\\\\\n\\\",\\n\",\n",
    "    \"    \\\"    --batch-size 4 \\\\\\\\\\\\n\\\",\\n\",\n",
    "    \"    \\\"    --grad-accum 4 \\\\\\\\\\\\n\\\",\\n\",\n",
    "    \"    \\\"    --lr 2e-4 \\\\\\\\\\\\n\\\",\\n\",\n",
    "    \"    \\\"    --lora-rank 16 \\\\\\\\\\\\n\\\",\\n\",\n",
    "    \"    \\\"    --lora-alpha 32\\\"\\n\",\n",
    "    \"   ],\\n\",\n",
    "    \"   \\\"execution_count\\\": null,\\n\",\n",
    "    \"   \\\"outputs\\\": []\\n\",\n",
    "    \"  },\\n\",\n",
    "    \"  {\\n\",\n",
    "    \"   \\\"cell_type\\\": \\\"code\\\",\\n\",\n",
    "    \"   \\\"metadata\\\": {},\\n\",\n",
    "    \"   \\\"source\\\": [\\n\",\n",
    "    \"    \\\"# Cell 6 — Merge adapter into base model\\\\n\\\",\\n\",\n",
    "    \"    \\\"!python src/merge_adapter.py \\\\\\\\\\\\n\\\",\\n\",\n",
    "    \"    \\\"    --adapter artifacts/lora_adapter/final_adapter \\\\\\\\\\\\n\\\",\\n\",\n",
    "    \"    \\\"    --output  artifacts/merged_model\\\\n\\\",\\n\",\n",
    "    \"    \\\"\\\\n\\\",\\n\",\n",
    "    \"    \\\"import pathlib\\\\n\\\",\\n\",\n",
    "    \"    \\\"size = sum(\\\\n\\\",\\n\",\n",
    "    \"    \\\"    p.stat().st_size \\\\n\\\",\\n\",\n",
    "    \"    \\\"    for p in pathlib.Path('artifacts/merged_model').rglob('*') \\\\n\\\",\\n\",\n",
    "    \"    \\\"    if p.is_file()\\\\n\\\",\\n\",\n",
    "    \"    \\\")\\\\n\\\",\\n\",\n",
    "    \"    \\\"print(f'Merged model size: {size/1e6:.0f} MB')\\\"\\n\",\n",
    "    \"   ],\\n\",\n",
    "    \"   \\\"execution_count\\\": null,\\n\",\n",
    "    \"   \\\"outputs\\\": []\\n\",\n",
    "    \"  },\\n\",\n",
    "    \"  {\\n\",\n",
    "    \"   \\\"cell_type\\\": \\\"code\\\",\\n\",\n",
    "    \"   \\\"metadata\\\": {},\\n\",\n",
    "    \"   \\\"source\\\": [\\n\",\n",
    "    \"    \\\"# Cell 7 — Quantize to GGUF\\\\n\\\",\\n\",\n",
    "    \"    \\\"!python src/quantize.py \\\\\\\\\\\\n\\\",\\n\",\n",
    "    \"    \\\"    --merged  artifacts/merged_model \\\\\\\\\\\\n\\\",\\n\",\n",
    "    \"    \\\"    --out-dir artifacts/quantized \\\\\\\\\\\\n\\\",\\n\",\n",
    "    \"    \\\"    --quant   Q4_K_M Q3_K_M\\\\n\\\",\\n\",\n",
    "    \"    \\\"\\\\n\\\",\\n\",\n",
    "    \"    \\\"import json, pathlib\\\\n\\\",\\n\",\n",
    "    \"    \\\"manifest = json.loads(\\\\n\\\",\\n\",\n",
    "    \"    \\\"    pathlib.Path('artifacts/quantized/manifest.json').read_text()\\\\n\\\",\\n\",\n",
    "    \"    \\\")\\\\n\\\",\\n\",\n",
    "    \"    \\\"for quant, info in manifest.items():\\\\n\\\",\\n\",\n",
    "    \"    \\\"    if quant != 'primary':\\\\n\\\",\\n\",\n",
    "    \"    \\\"        print(f'{quant}: {info[\\\\\\\"size_mb\\\\\\\"]:.1f} MB')\\\"\\n\",\n",
    "    \"   ],\\n\",\n",
    "    \"   \\\"execution_count\\\": null,\\n\",\n",
    "    \"   \\\"outputs\\\": []\\n\",\n",
    "    \"  },\\n\",\n",
    "    \"  {\\n\",\n",
    "    \"   \\\"cell_type\\\": \\\"code\\\",\\n\",\n",
    "    \"   \\\"metadata\\\": {},\\n\",\n",
    "    \"   \\\"source\\\": [\\n\",\n",
    "    \"    \\\"# Cell 8 — Check hard gates\\\\n\\\",\\n\",\n",
    "    \"    \\\"# Gate 1: No network imports\\\\n\\\",\\n\",\n",
    "    \"    \\\"from starter.eval_harness_contract import check_no_network_imports\\\\n\\\",\\n\",\n",
    "    \"    \\\"ok = check_no_network_imports('inference.py')\\\\n\\\",\\n\",\n",
    "    \"    \\\"print(f'Network import gate: {\\\\\\\"PASS\\\\\\\" if ok else \\\\\\\"FAIL\\\\\\\"}')\\\\n\\\",\\n\",\n",
    "    \"    \\\"\\\\n\\\",\\n\",\n",
    "    \"    \\\"# Gate 2: Model size\\\\n\\\",\\n\",\n",
    "    \"    \\\"import pathlib, json\\\\n\\\",\\n\",\n",
    "    \"    \\\"m = pathlib.Path('artifacts/quantized/manifest.json')\\\\n\\\",\\n\",\n",
    "    \"    \\\"if m.exists():\\\\n\\\",\\n\",\n",
    "    \"    \\\"    d = json.loads(m.read_text())\\\\n\\\",\\n\",\n",
    "    \"    \\\"    p = d.get(d.get('primary','Q4_K_M'),{}).get('path','')\\\\n\\\",\\n\",\n",
    "    \"    \\\"    if p and pathlib.Path(p).exists():\\\\n\\\",\\n\",\n",
    "    \"    \\\"        sz = pathlib.Path(p).stat().st_size / 1e6\\\\n\\\",\\n\",\n",
    "    \"    \\\"        print(f'Model size: {sz:.1f} MB')\\\\n\\\",\\n\",\n",
    "    \"    \\\"        print(f'500 MB gate: {\\\\\\\"PASS\\\\\\\" if sz <= 500 else \\\\\\\"FAIL\\\\\\\"}')\\\\n\\\",\\n\",\n",
    "    \"    \\\"        print(f'250 MB gate: {\\\\\\\"PASS\\\\\\\" if sz <= 250 else \\\\\\\"FAIL\\\\\\\"}')\\\"\\n\",\n",
    "    \"   ],\\n\",\n",
    "    \"   \\\"execution_count\\\": null,\\n\",\n",
    "    \"   \\\"outputs\\\": []\\n\",\n",
    "    \"  },\\n\",\n",
    "    \"  {\\n\",\n",
    "    \"   \\\"cell_type\\\": \\\"code\\\",\\n\",\n",
    "    \"   \\\"metadata\\\": {},\\n\",\n",
    "    \"   \\\"source\\\": [\\n\",\n",
    "    \"    \\\"# Cell 9 — Smoke test inference\\\\n\\\",\\n\",\n",
    "    \"    \\\"!python inference.py\\\"\\n\",\n",
    "    \"   ],\\n\",\n",
    "    \"   \\\"execution_count\\\": null,\\n\",\n",
    "    \"   \\\"outputs\\\": []\\n\",\n",
    "    \"  },\\n\",\n",
    "    \"  {\\n\",\n",
    "    \"   \\\"cell_type\\\": \\\"code\\\",\\n\",\n",
    "    \"   \\\"metadata\\\": {},\\n\",\n",
    "    \"   \\\"source\\\": [\\n\",\n",
    "    \"    \\\"# Cell 10 — Evaluate on public test set\\\\n\\\",\\n\",\n",
    "    \"    \\\"!python src/evaluate.py \\\\\\\\\\\\n\\\",\\n\",\n",
    "    \"    \\\"    --test      starter/public_test.jsonl \\\\\\\\\\\\n\\\",\\n\",\n",
    "    \"    \\\"    --inference inference.py \\\\\\\\\\\\n\\\",\\n\",\n",
    "    \"    \\\"    --latency \\\\\\\\\\\\n\\\",\\n\",\n",
    "    \"    \\\"    --verbose\\\"\\n\",\n",
    "    \"   ],\\n\",\n",
    "    \"   \\\"execution_count\\\": null,\\n\",\n",
    "    \"   \\\"outputs\\\": []\\n\",\n",
    "    \"  },\\n\",\n",
    "    \"  {\\n\",\n",
    "    \"   \\\"cell_type\\\": \\\"code\\\",\\n\",\n",
    "    \"   \\\"metadata\\\": {},\\n\",\n",
    "    \"   \\\"source\\\": [\\n\",\n",
    "    \"    \\\"# Cell 11 — Evaluate each slice separately\\\\n\\\",\\n\",\n",
    "    \"    \\\"import subprocess\\\\n\\\",\\n\",\n",
    "    \"    \\\"for sl in ['A', 'B', 'C', 'D']:\\\\n\\\",\\n\",\n",
    "    \"    \\\"    print(f'\\\\\\\\n==== SLICE {sl} ====')\\\\n\\\",\\n\",\n",
    "    \"    \\\"    subprocess.run([\\\\n\\\",\\n\",\n",
    "    \"    \\\"        'python', 'src/evaluate.py',\\\\n\\\",\\n\",\n",
    "    \"    \\\"        '--test',      'starter/public_test.jsonl',\\\\n\\\",\\n\",\n",
    "    \"    \\\"        '--inference', 'inference.py',\\\\n\\\",\\n\",\n",
    "    \"    \\\"        '--slice',     sl\\\\n\\\",\\n\",\n",
    "    \"    \\\"    ])\\\"\\n\",\n",
    "    \"   ],\\n\",\n",
    "    \"   \\\"execution_count\\\": null,\\n\",\n",
    "    \"   \\\"outputs\\\": []\\n\",\n",
    "    \"  },\\n\",\n",
    "    \"  {\\n\",\n",
    "    \"   \\\"cell_type\\\": \\\"code\\\",\\n\",\n",
    "    \"   \\\"metadata\\\": {},\\n\",\n",
    "    \"   \\\"source\\\": [\\n\",\n",
    "    \"    \\\"# Cell 12 — Push results back to GitHub\\\\n\\\",\\n\",\n",
    "    \"    \\\"import os\\\\n\\\",\\n\",\n",
    "    \"    \\\"\\\\n\\\",\\n\",\n",
    "    \"    \\\"GITHUB_USERNAME = 'YourName'\\\\n\\\",\\n\",\n",
    "    \"    \\\"GITHUB_TOKEN    = 'ghp_your_token_here'\\\\n\\\",\\n\",\n",
    "    \"    \\\"GITHUB_EMAIL    = 'your@email.com'\\\\n\\\",\\n\",\n",
    "    \"    \\\"\\\\n\\\",\\n\",\n",
    "    \"    \\\"os.environ['GIT_AUTHOR_NAME']     = GITHUB_USERNAME\\\\n\\\",\\n\",\n",
    "    \"    \\\"os.environ['GIT_AUTHOR_EMAIL']    = GITHUB_EMAIL\\\\n\\\",\\n\",\n",
    "    \"    \\\"os.environ['GIT_COMMITTER_NAME']  = GITHUB_USERNAME\\\\n\\\",\\n\",\n",
    "    \"    \\\"os.environ['GIT_COMMITTER_EMAIL'] = GITHUB_EMAIL\\\\n\\\",\\n\",\n",
    "    \"    \\\"\\\\n\\\",\\n\",\n",
    "    \"    \\\"!git config user.email \\\\\\\"{GITHUB_EMAIL}\\\\\\\"\\\\n\\\",\\n\",\n",
    "    \"    \\\"!git config user.name  \\\\\\\"{GITHUB_USERNAME}\\\\\\\"\\\\n\\\",\\n\",\n",
    "    \"    \\\"\\\\n\\\",\\n\",\n",
    "    \"    \\\"REMOTE = f'https://{GITHUB_USERNAME}:{GITHUB_TOKEN}@github.com/{GITHUB_USERNAME}/tool-calling-agent.git'\\\\n\\\",\\n\",\n",
    "    \"    \\\"!git remote set-url origin {REMOTE}\\\\n\\\",\\n\",\n",
    "    \"    \\\"\\\\n\\\",\\n\",\n",
    "    \"    \\\"!git add .\\\\n\\\",\\n\",\n",
    "    \"    \\\"!git commit -m 'Add trained model artifacts'\\\\n\\\",\\n\",\n",
    "    \"    \\\"!git push origin main\\\\n\\\",\\n\",\n",
    "    \"    \\\"\\\\n\\\",\\n\",\n",
    "    \"    \\\"print('Pushed to GitHub!')\\\"\\n\",\n",
    "    \"   ],\\n\",\n",
    "    \"   \\\"execution_count\\\": null,\\n\",\n",
    "    \"   \\\"outputs\\\": []\\n\",\n",
    "    \"  },\\n\",\n",
    "    \"  {\\n\",\n",
    "    \"   \\\"cell_type\\\": \\\"code\\\",\\n\",\n",
    "    \"   \\\"metadata\\\": {},\\n\",\n",
    "    \"   \\\"source\\\": [\\n\",\n",
    "    \"    \\\"# Cell 13 — Launch Gradio demo\\\\n\\\",\\n\",\n",
    "    \"    \\\"# Creates public link anyone can open\\\\n\\\",\\n\",\n",
    "    \"    \\\"!python demo/app.py --share\\\"\\n\",\n",
    "    \"   ],\\n\",\n",
    "    \"   \\\"execution_count\\\": null,\\n\",\n",
    "    \"   \\\"outputs\\\": []\\n\",\n",
    "    \"  },\\n\",\n",
    "    \"  {\\n\",\n",
    "    \"   \\\"cell_type\\\": \\\"code\\\",\\n\",\n",
    "    \"   \\\"metadata\\\": {},\\n\",\n",
    "    \"   \\\"source\\\": [\\n\",\n",
    "    \"    \\\"# Cell 14 — Download model file to your computer\\\\n\\\",\\n\",\n",
    "    \"    \\\"from google.colab import files\\\\n\\\",\\n\",\n",
    "    \"    \\\"import pathlib, json\\\\n\\\",\\n\",\n",
    "    \"    \\\"\\\\n\\\",\\n\",\n",
    "    \"    \\\"manifest_path = pathlib.Path('artifacts/quantized/manifest.json')\\\\n\\\",\\n\",\n",
    "    \"    \\\"if manifest_path.exists():\\\\n\\\",\\n\",\n",
    "    \"    \\\"    manifest  = json.loads(manifest_path.read_text())\\\\n\\\",\\n\",\n",
    "    \"    \\\"    primary   = manifest.get('primary', 'Q4_K_M')\\\\n\\\",\\n\",\n",
    "    \"    \\\"    gguf_path = manifest.get(primary, {}).get('path', '')\\\\n\\\",\\n\",\n",
    "    \"    \\\"    if gguf_path and pathlib.Path(gguf_path).exists():\\\\n\\\",\\n\",\n",
    "    \"    \\\"        size_mb = pathlib.Path(gguf_path).stat().st_size / 1e6\\\\n\\\",\\n\",\n",
    "    \"    \\\"        print(f'Downloading {gguf_path} ({size_mb:.0f} MB)')\\\\n\\\",\\n\",\n",
    "    \"    \\\"        files.download(gguf_path)\\\\n\\\",\\n\",\n",
    "    \"    \\\"    else:\\\\n\\\",\\n\",\n",
    "    \"    \\\"        print('GGUF file not found')\\\\n\\\",\\n\",\n",
    "    \"    \\\"else:\\\\n\\\",\\n\",\n",
    "    \"    \\\"    print('Run quantize step first')\\\"\\n\",\n",
    "    \"   ],\\n\",\n",
    "    \"   \\\"execution_count\\\": null,\\n\",\n",
    "    \"   \\\"outputs\\\": []\\n\",\n",
    "    \"  }\\n\",\n",
    "    \" ]\\n\",\n",
    "    \"}\"\n",
    "   ]\n",
    "  }\n",
    " ],\n",
    " \"metadata\": {\n",
    "  \"kernelspec\": {\n",
    "   \"display_name\": \"Python 3\",\n",
    "   \"language\": \"python\",\n",
    "   \"name\": \"python3\"\n",
    "  },\n",
    "  \"language_info\": {\n",
    "   \"codemirror_mode\": {\n",
    "    \"name\": \"ipython\",\n",
    "    \"version\": 3\n",
    "   },\n",
    "   \"file_extension\": \".py\",\n",
    "   \"mimetype\": \"text/x-python\",\n",
    "   \"name\": \"python\",\n",
    "   \"nbconvert_exporter\": \"python\",\n",
    "   \"pygments_lexer\": \"ipython3\",\n",
    "   \"version\": \"3.14.3\"\n",
    "  }\n",
    " },\n",
    " \"nbformat\": 4,\n",
    " \"nbformat_minor\": 5\n",
    "}"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.14.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
